export const functionKey = [
  "F1",
  "F2",
  "F3",
  "F4",
  "F5",
  "F6",
  "F7",
  "F8",
  "F9",
  "F10",
  "F11",
  "F12",
];

export const codeToHangul: Record<string, { normal: string; shift: string }> = {
  KeyQ: { normal: "ㅂ", shift: "ㅃ" },
  KeyW: { normal: "ㅈ", shift: "ㅉ" },
  KeyE: { normal: "ㄷ", shift: "ㄸ" },
  KeyR: { normal: "ㄱ", shift: "ㄲ" },
  KeyT: { normal: "ㅅ", shift: "ㅆ" },
  KeyY: { normal: "ㅛ", shift: "ㅛ" },
  KeyU: { normal: "ㅕ", shift: "ㅕ" },
  KeyI: { normal: "ㅑ", shift: "ㅑ" },
  KeyO: { normal: "ㅐ", shift: "ㅒ" },
  KeyP: { normal: "ㅔ", shift: "ㅖ" },
  KeyA: { normal: "ㅁ", shift: "ㅁ" },
  KeyS: { normal: "ㄴ", shift: "ㄴ" },
  KeyD: { normal: "ㅇ", shift: "ㅇ" },
  KeyF: { normal: "ㄹ", shift: "ㄹ" },
  KeyG: { normal: "ㅎ", shift: "ㅎ" },
  KeyH: { normal: "ㅗ", shift: "ㅗ" },
  KeyJ: { normal: "ㅓ", shift: "ㅓ" },
  KeyK: { normal: "ㅏ", shift: "ㅏ" },
  KeyL: { normal: "ㅣ", shift: "ㅣ" },
  KeyZ: { normal: "ㅋ", shift: "ㅋ" },
  KeyX: { normal: "ㅌ", shift: "ㅌ" },
  KeyC: { normal: "ㅊ", shift: "ㅊ" },
  KeyV: { normal: "ㅍ", shift: "ㅍ" },
  KeyB: { normal: "ㅠ", shift: "ㅠ" },
  KeyN: { normal: "ㅜ", shift: "ㅜ" },
  KeyM: { normal: "ㅡ", shift: "ㅡ" },
};
